<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FitnessCenter.Core\FitnessCenter.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.13" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.13" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.13" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.13" />
    <PackageReference Include="MongoDB.Bson" Version="3.8.1" />
    <PackageReference Include="MongoDB.Driver" Version="3.8.1" />
    <PackageReference Include="Neo4j.Driver" Version="5.15.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
  </ItemGroup>

</Project>