<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="DTO\Services\MongoDB\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="LF.EntityFramework.Extention" Version="2.0.1" />
    </ItemGroup>

</Project>
