<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FitnessCenter.Core\FitnessCenter.Core.csproj" />
    <ProjectReference Include="..\FitnessCenter.Infrastructure\FitnessCenter.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.13" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.13" />
    <PackageReference Include="MongoDB.Driver" Version="3.8.1" />
    <PackageReference Include="Neo4j.Driver" Version="5.15.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>